export const CATEGORIES_AND_SUBCATEGORIES_LOADED =
  "ADD_CATEGORIES_AND_SUBCATEGORIES";
export const CATEGORIES_AND_SUBCATEGORIES_LOADING =
  "CATEGORIES_AND_SUBCATEGORIES_LOADING";
export const CATEGORIES_AND_SUBCATEGORIES_FAILED =
  "CATEGORIES_AND_SUBCATEGORIES_FAILED";
export const ADD_SUBCATEGORIES_MAP = "ADD_SUBCATEGORIES_MAP";
export const SUBCATEGORIES_MAP_CHARGE = "SUBCATEGORIES_MAP_CHARGE";

export const DATA_POINTS_LOADED = "DATA_POINTS_LOADED";
export const DATA_POINTS_FAILED = "DATA_POINTS_FAILED";

export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const REQUEST_SIGNUP = "REQUEST_SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const LANDING_STATS_LOADED = "LANDING_STATS_LOADED";
export const LANDING_STATS_LOADING = "LANDING_STATS_LOADING";
export const LANDING_STATS_FAILED = "LANDING_STATS_FAILED";
